name: "Build Schemas"
description: "build schemas"
inputs:
  version:
    description: "Version number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 18

    - name: Make Config
      working-directory: ./src/cloudeventjekylldocs
      shell: bash
      run: make config

    - name: Make Build
      working-directory: ./src/cloudeventjekylldocs
      shell: bash
      run: make build

    - name: tar schema
      run: tar -cvf artifact.tar src/cloudeventjekylldocs/output/schemas"
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        path: "artifact.tar"
        name: schemas-${{ inputs.version }}
