repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-added-large-files
        exclude: |
          (?x)^(
            docs/assets/aws-icons-mermaid.json |
            src/eventcatalog/package-lock.json
          )$
      - id: check-symlinks
      - id: detect-private-key
        exclude: |
          (?x)^(
            .*/validate-private-key\.test\.ts |
            utils/utils/src/__tests__/key-generation/get-private-key.test.ts
          )$
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix']
        exclude: |
          (?x)^(
            .*/?package-lock.json |
            docs/assets/js/zzzz-search-data.json |
            packages/event-schemas/schemas/[^/]+/[^/]+\.json
          )$
    # -   id: ...

  - repo: https://github.com/NHSDigital/nhs-notify-shared-modules
    rev: 3.1.2
    hooks:
      - id: sort-dictionary
      - id: scan-secrets
        args: [check=whole-history]
      - id: check-file-format
        args: [check=branch]
      - id: check-markdown-format
        args: [check=branch]
      - id: check-english-usage
        args: [check=branch]
      - id: lint-terraform
      - id: generate-terraform-docs
      - id: check-todo-usage
        args: [check=branch]
