[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = dl_utils/__tests__
addopts = -v --tb=short

[coverage:run]
relative_files = True
data_file = utils/py-utils/.coverage
omit =
    */dl_utils/__tests__/*
    */test_*.py
    */__pycache__/*
    */venv/*
    */.venv/*
    */env/*
