name: 'Node install and setup'
description: 'Setup node and authenticate github package repository'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
  GITHUB_TOKEN:
    description: "Token for access to github package registry"
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Use Node.js'
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: '${{ inputs.node-version }}'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: "Configure npm for GitHub Packages"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        scripts/set-github-token.sh
